// for Login Api Action
export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

// Sign Up
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Sign out
export const SIGN_OUT = "SIGN_OUT";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// New User Count
export const GET_NEW_USER_REQUEST_COUNT_INIT =
  "GET_NEW_USER_REQUEST_COUNT_INIT";
export const GET_NEW_USER_REQUEST_COUNT_SUCCESS =
  "GET_NEW_USER_REQUEST_COUNT_SUCCESS";
export const GET_NEW_USER_REQUEST_COUNT_FAIL =
  "GET_NEW_USER_REQUEST_COUNT_FAIL";

// Cleare Responce Message
export const CLEARE_SECURITY_ADMIN_RESPONCE_MESSAGE =
  "CLEARE_SECURITY_ADMIN_RESPONCE_MESSAGE";

// For New User Requests
export const GET_NEW_USER_REQUESTS_INIT = "GET_NEW_USER_REQUESTS_INIT";
export const GET_NEW_USER_REQUESTS_SUCCESS = "GET_NEW_USER_REQUESTS_SUCCESS";
export const GET_NEW_USER_REQUESTS_FAIL = "GET_NEW_USER_REQUESTS_FAIL";

// For Save User
export const SAVE_USER_INIT = "SAVE_USER_INIT";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";

// For Edit User
export const EDIT_USER_INIT = "EDIT_USER_INIT";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

//For Get All User List
export const GET_ALL_USER_LIST_INIT = "GET_ALL_USER_LIST_INIT";
export const GET_ALL_USER_LIST_SUCCESS = "GET_ALL_USER_LIST_SUCCESS";
export const GET_ALL_USER_LIST_FAIL = "GET_ALL_USER_LIST_FAIL";

// For get All User Role List
export const GET_ALL_USER_ROLE_LIST_INIT = "GET_ALL_USER_ROLE_LIST_INIT";
export const GET_ALL_USER_ROLE_LIST_SUCCESS = "GET_ALL_USER_ROLE_LIST_SUCCESS";
export const GET_ALL_USER_ROLE_LIST_FAIL = "GET_ALL_USER_ROLE_LIST_FAIL";

// For Get All User Status
export const GET_ALL_USER_STATUS_INIT = "GET_ALL_USER_STATUS_INIT";
export const GET_ALL_USER_STATUS_SUCCESS = "GET_ALL_USER_STATUS_SUCCESS";
export const GET_ALL_USER_STATUS_FAIL = "GET_ALL_USER_STATUS_FAIL";

// For Get Reject User Request
export const GET_REJECT_USER_INIT = "GET_REJECT_USER_INIT";
export const GET_REJECT_USER_SUCCESS = "GET_REJECT_USER_SUCCESS";
export const GET_REJECT_USER_FAIL = "GET_REJECT_USER_FAIL";

// For Create Add A Bank User
export const CREATE_BANK_USER_INIT = "CREATE_BANK_USER_INIT";
export const CREATE_BANK_USER_SUCCESS = "CREATE_BANK_USER_SUCCESS";
export const CREATE_BANK_USER_FAIL = "CREATE_BANK_USER_FAIL";

//For Get All Corporate Api
export const GET_ALL_CORPORATES_INIT = "GET_ALL_CORPORATES_INIT";
export const GET_ALL_CORPORATES_SUCCESS = "GET_ALL_CORPORATES_SUCCESS";
export const GET_ALL_CORPORATES_FAIL = "GET_ALL_CORPORATES_FAIL";

//For Get All Corporate Category Api
export const GET_ALL_CORPORATES_CATEGORY_INIT =
  "GET_ALL_CORPORATES_CATEGORY_INIT";
export const GET_ALL_CORPORATES_CATEGORY_SUCCESS =
  "GET_ALL_CORPORATES_CATEGORY_SUCCESS";
export const GET_ALL_CORPORATES_CATEGORY_FAIL =
  "GET_ALL_CORPORATES_CATEGORY_FAIL";

//For Create Corporate New User
export const CREATE_CORPORATE_USER_INIT = "CREATE_CORPORATE_USER_INIT";
export const CREATE_CORPORATE_USER_SUCCESS = "CREATE_CORPORATE_USER_SUCCESS";
export const CREATE_CORPORATE_USER_FAIL = "CREATE_CORPORATE_USER_FAIL";

//For Create New Corporate
export const NEW_CORPORATE_CREATE_INIT = "NEW_CORPORATE_CREATE_INIT";
export const NEW_CORPORATE_CREATE_SUCCESS = "NEW_CORPORATE_CREATE_SUCCESS";
export const NEW_CORPORATE_CREATE_FAIL = "NEW_CORPORATE_CREATE_FAIL";

// For get All Nature of Business
export const GET_ALL_NATURE_BUSINESS_INIT = "GET_ALL_NATURE_BUSINESS_INIT";
export const GET_ALL_NATURE_BUSINESS_SUCCESS =
  "GET_ALL_NATURE_BUSINESS_SUCCESS";
export const GET_ALL_NATURE_BUSINESS_FAIL = "GET_ALL_NATURE_BUSINESS_FAIL";

// For get all assets types API
export const GET_ALL_ASSETS_TYPE_INIT = "GET_ALL_ASSETS_TYPE_INIT";
export const GET_ALL_ASSETS_TYPE_SUCCESS = "GET_ALL_ASSETS_TYPE_SUCCESS";
export const GET_ALL_ASSETS_TYPE_FAIL = "GET_ALL_ASSETS_TYPE_FAIL";

//fOR BULK USER LIST
export const Get_ALL_BULK_USER_INIT = "Get_ALL_BULK_USER_INIT";
export const GET_AL_BULK_USER_SUCCESS = "GET_AL_BULK_USER_SUCCESS";
export const GET_ALL_BULK_USER_FAIL = "GET_ALL_BULK_USER_FAIL";
export const RESET_ALL_FILES_UPLOAD = "RESET_ALL_FILES_UPLOAD";

// Corporate Users
export const GET_ALL_CORPORATE_USERS_INIT = "GET_ALL_CORPORATE_USERS_INIT";
export const GET_ALL_CORPORATE_USERS_SUCCESS =
  "GET_ALL_CORPORATE_USERS_SUCCESS";
export const GET_ALL_CORPORATE_USERS_FAIL = "GET_ALL_CORPORATE_USERS_FAIL";

//SearchCorporateUser
export const SEARCH_CORPORATE_USER_INIT = "SEARCH_CORPORATE_USER_INIT";
export const SEARCH_CORPORATE_USER_SUCCESS = "SEARCH_CORPORATE_USER_SUCCESS";
export const SEARCH_CORPORATE_USER_FAIL = "SEARCH_CORPORATE_USER_FAIL";

//for Get All Bank User API
export const GET_ALL_BANK_CORPORATE_INIT = "GET_ALL_BANK_CORPORATE_INIT";
export const GET_ALL_BANK_CORPORATE_SUCCESS = "GET_ALL_BANK_CORPORATE_SUCCESS";
export const GET_ALL_BANK_CORPORATE_FAIL = "GET_ALL_BANK_CORPORATE_FAIL";

// For Update Corporate User Api
export const UPDATE_CORPORATE_USER_INIT = "UPDATE_CORPORATE_USER_INIT";
export const UPDATE_CORPORATE_USER_SUCCESS = "UPDATE_CORPORATE_USER_SUCCESS";
export const UPDATE_CORPORATE_USER_FAIL = "UPDATE_CORPORATE_USER_FAIL";

// for get all corporate name by bank ID for company dropdown
export const GET_ALL_CORPORATE_NAME_BY_BANK_INIT =
  "GET_ALL_CORPORATE_NAME_BY_BANK_INIT";
export const GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS =
  "GET_ALL_CORPORATE_NAME_BY_BANK_SUCCESS";
export const GET_ALL_CORPORATE_NAME_BY_BANK_FAIL =
  "GET_ALL_CORPORATE_NAME_BY_BANK_FAIL";

// FOR ADD NATURE OF BUSINESS IN NATURE BUSINESS PAGE
export const ADD_NATURE_OF_BUSINESS_INIT = "ADD_NATURE_OF_BUSINESS_INIT";
export const ADD_NATURE_OF_BUSINESS_SUCCESS = "ADD_NATURE_OF_BUSINESS_SUCCESS";
export const ADD_NATURE_OF_BUSINESS_FAIL = "ADD_NATURE_OF_BUSINESS_FAIL";

// FOR UPDATE NATURE OF BUSINESS IN NATURE BUSINESS PAGE
export const UPDATE_NATURE_OF_BUSINESS_INIT = "UPDATE_NATURE_OF_BUSINESS_INIT";
export const UPDATE_NATURE_OF_BUSINESS_SUCCESS =
  "UPDATE_NATURE_OF_BUSINESS_SUCCESS";
export const UPDATE_NATURE_OF_BUSINESS_FAIL = "UPDATE_NATURE_OF_BUSINESS_FAIL";

// FOR VIEW NATURE OF BUSINESS IN NATURE BUSINESS PAGE API FOR PAGINATION
export const VIEW_NATURE_BUSINESS_INIT = "VIEW_NATURE_BUSINESS_INIT";
export const VIEW_NATURE_BUSINESS_SUCCESS = "VIEW_NATURE_BUSINESS_SUCCESS";
export const VIEW_NATURE_BUSINESS_FAIL = "VIEW_NATURE_BUSINESS_FAIL";

// FOR DELETE NATURE OF BUSINESS IN NATURE BUSINESS PAGE API
export const DELETE_NATURE_BUSINESS_INIT = "DELETE_NATURE_BUSINESS_INIT";
export const DELETE_NATURE_BUSINESS_SUCCESS = "DELETE_NATURE_BUSINESS_SUCCESS";
export const DELETE_NATURE_BUSINESS_FAIL = "DELETE_NATURE_BUSINESS_FAIL";

// for download add customer Excel File
export const DOWNLOAD_ADD_BANK_EXCEL_INIT = "DOWNLOAD_ADD_BANK_EXCEL_INIT";

//for download Report Loader Api
export const DOWNLOAD_REPORT_INIT = "DOWNLOAD_REPORT_INIT";

//for download something went wrong
export const SOME_THING_WENT_WRONG = "SOME_THING_WENT_WRONG";

// for downlaod Access Report Api
export const DOWNLOAD_ACCESS_REPORT_INIT = "DOWNLOAD_ACCESS_REPORT_INIT";

// for download STatus wise report
export const DOWNLOAD_STATUSWISE_REPORT_INIT =
  "DOWNLOAD_STATUSWISE_REPORT_INIT";

// for download Last Login report
export const DOWNLOAD_LASTLOGIN_REPORT_INIT = "DOWNLOAD_LASTLOGIN_REPORT_INIT";

// for download bank User login History Excel File
export const DOWNLOAD_EXCEL_BANK_FILE_INIT = "DOWNLOAD_EXCEL_BANK_FILE_INIT";
