// for Login Api Action
export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

// Sign Up
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Sign out
export const SIGN_OUT = "SIGN_OUT";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// New User Count
export const GET_NEW_USER_REQUEST_COUNT_INIT =
  "GET_NEW_USER_REQUEST_COUNT_INIT";
export const GET_NEW_USER_REQUEST_COUNT_SUCCESS =
  "GET_NEW_USER_REQUEST_COUNT_SUCCESS";
export const GET_NEW_USER_REQUEST_COUNT_FAIL =
  "GET_NEW_USER_REQUEST_COUNT_FAIL";

// Cleare Responce Message
export const CLEARE_SECURITY_ADMIN_RESPONCE_MESSAGE =
  "CLEARE_SECURITY_ADMIN_RESPONCE_MESSAGE";

// For New User Requests
export const GET_NEW_USER_REQUESTS_INIT = "GET_NEW_USER_REQUESTS_INIT";
export const GET_NEW_USER_REQUESTS_SUCCESS = "GET_NEW_USER_REQUESTS_SUCCESS";
export const GET_NEW_USER_REQUESTS_FAIL = "GET_NEW_USER_REQUESTS_FAIL";

// For Save User
export const SAVE_USER_INIT = "SAVE_USER_INIT";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";

// For Edit User
export const EDIT_USER_INIT = "EDIT_USER_INIT";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

//For Get All User List
export const GET_ALL_USER_LIST_INIT = "GET_ALL_USER_LIST_INIT";
export const GET_ALL_USER_LIST_SUCCESS = "GET_ALL_USER_LIST_SUCCESS";
export const GET_ALL_USER_LIST_FAIL = "GET_ALL_USER_LIST_FAIL";
